### PR TITLE
fix: add download message on mac

### PR DESCRIPTION
**Pull request by 2fd**
This PR shows the same message we already show on windows but now in mac

Screen Shot 2022-08-05 at 16 48 20

### CODE REVIEW

**Comment by menduz** [comment]
Should we add a killswitch with feature flags?

**Comment by 2fd** [comment]
@menduz we can add it if there is a change that we need to take it down. Is that the case?

**Review by fzavalia — APPROVED** [review]
LGTM

**Comment by menduz** [comment]
@2fd yes, that's the use case

**Pull request merged**
