### PR TITLE
fix: listen to WAITING_RENDERER for the loading status

### LINKED ISSUE #74: Show a loading screen after selecting the wallet
> When I click on the Metamask icon  in this screen, and I don’t need to sign again bc I had already loaded, the screen stays stuck there for like 5 seconds before anything happens
A lot of times I thought it was stuck and I reloaded, because I didn’t see any feedback when I clicked. It took me several times to realize that it was working fine and I just needed to let it load a few seconds
If there was some kind of feedback happening there it would make all the difference
Screen Shot 2021-09-27 at 12 57 59

### PR DESCRIPTION
**Pull request by nicosantangelo**
A new LoginState was added to the kernel-interface ( https://github.com/decentraland/kernel-interface/commit/017905de24c5267e7146d4152b512205265a63b1 ) but wasn't being taken into account in the explorer website 

Closes #74

### CODE REVIEW

**Review by menduz — APPROVED** [review]
:shipit:

**Comment by menduz** [comment]
Weird, I'm AFK but it is strange that it didn't merge automatically. Can't figure why

**Review by kuruk-mm — APPROVED** [review]
Nice!

**Comment by kuruk-mm** [comment]
> Weird, I'm AFK but it is strange that it didn't merge automatically. Can't figure why

Commit not verified?

> Weird, I'm AFK but it is strange that it didn't merge automatically. Can't figure why

Maybe the option to merge only signed commits is enabled?

**Comment by kuruk-mm** [comment]
> Weird, I'm AFK but it is strange that it didn't merge automatically. Can't figure why

Maybe the option to merge only signed commits is enabled?

**Comment by menduz** [comment]
@nicosantangelo may we disable the signed commit restriction to merge? PS: please sign the commits

**Comment by nicosantangelo** [comment]
Will sign 👍

**Pull request merged**
