### PR TITLE
chore: update decentraland ui

### PR DESCRIPTION
**Pull request by 2fd**

### CODE REVIEW

**Comment by menduz** [comment]
`+56,318 −454`?

**Comment by 2fd** [comment]
because I run the upgrade with the wrong node version, we eventually will need to upgrade the `package-lock` to version 2

**Comment by 2fd** [comment]
I re-run the upgrade with version 1 and also upgrade react to include changes from #298

**Comment by 2fd** [comment]
@menduz what do you think now?

**Comment by menduz** [comment]
I'd say to migrate to lockversion2 all repos and pull the band aid @2fd

**Comment by 2fd** [comment]
@menduz done. I just need one approved

**Review by menduz — APPROVED** [review]

**Pull request merged**
